---
deployment:
 tasks:
 - export DEPLOYPATH=/home/user/public_html/
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp -R css $DEPLOYPATH
 - /bin/cp -R functions $DEPLOYPATH
 - /bin/cp -R images $DEPLOYPATH
 - /bin/cp -R js $DEPLOYPATH